/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
import java.sql.*;
import java.sql.DriverManager;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MADHURENDRA PURBAY
 */
public class ig_from extends javax.swing.JFrame {
 Connection con=null;
 ResultSet rs=null,rs1=null;
    PreparedStatement pstmt=null;
    void last_data()
    {
         try 
        {
           Statement st=con.createStatement();   
           ResultSet rs=st.executeQuery("select *from sp where pref_no=1 ");
           String srno;
           String from;
           String to,dat,remark,date = null;
           DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
           while (true)
           {
               int c=tm.getRowCount();
               if(c==0)
                   break;
               else 
                   tm.removeRow(0);
           }
           while(rs.next())
           {
              srno=rs.getString("serial_no");
               from=rs.getString("from1");
               to=rs.getString("to");
               dat=rs.getString("date");
               remark=rs.getString("remarks");
                try
                {
                    SimpleDateFormat simpledateformat1 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
                    java.util.Date tempDate1=simpledateformat1.parse(dat);
                    SimpleDateFormat outputDateFormat1 = new SimpleDateFormat("dd-MMM-yyyy");
                    //System.out.println("Output date is = "+outputDateFormat.format(tempDate));
                    date=outputDateFormat1.format(tempDate1);
                     } catch (ParseException ex)
                {
                    System.out.println("Parse Exception");
                }

               Object kk[]={srno,date,from,to,remark};
               tm.addRow(kk);
           }
       }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connection "+e);
        }
    }

    /**
     * Creates new form ig_from
     */
    public ig_from() {
        initComponents();
         try
        {
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\dispatch.accdb");
        }
        catch(Exception e)
        {
            System.out.println(e);
             JOptionPane.showMessageDialog(null,"Database connection error","Error",JOptionPane.ERROR_MESSAGE);
        }
  last_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtletter_no_date = new com.toedter.calendar.JDateChooser();
        txtfrom1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtletter_no = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtsno = new javax.swing.JTextField();
        txtrecieved_date = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtremarks = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtm = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 10, 600, 150);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("प्रेषण खंड(आवक)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 150, 250, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Developed By: Madhurendra & Vishal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 650, 240, 60);

        txtletter_no_date.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txtletter_no_date);
        txtletter_no_date.setBounds(790, 320, 140, 30);

        txtfrom1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtfrom1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IG  Bastar", "IG  Bilapsur", "IG  Durg", "IG  Raipur", "IG  Sargoja  ", "others" }));
        jPanel1.add(txtfrom1);
        txtfrom1.setBounds(440, 320, 150, 30);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText(" टिप्पणी");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1120, 280, 120, 30);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("से");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 280, 100, 30);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("मामला (संक्षेप में)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(970, 370, 160, 30);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("पुलिस महानिरीक्षक");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(650, 210, 230, 30);

        submit.setBackground(new java.awt.Color(204, 204, 204));
        submit.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 102, 102));
        submit.setText("जमा करें");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(1030, 520, 110, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("वापस");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 500, 100, 30);

        txtletter_no.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtletter_no);
        txtletter_no.setBounds(640, 320, 120, 30);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("क्रमांक");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 280, 70, 30);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("खोज");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1030, 220, 110, 30);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("पत्र संख्या");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(640, 280, 130, 30);

        txtsno.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtsno);
        txtsno.setBounds(90, 320, 70, 30);

        txtrecieved_date.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txtrecieved_date);
        txtrecieved_date.setBounds(200, 320, 140, 30);

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("प्राप्त तारीख");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 280, 120, 30);

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("पत्र नंबर की तारीख");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(790, 280, 150, 30);

        txtremarks.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtremarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremarksActionPerformed(evt);
            }
        });
        jPanel1.add(txtremarks);
        txtremarks.setBounds(1120, 320, 130, 30);

        jLabel12.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("को");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(990, 280, 50, 30);

        txtto.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttoActionPerformed(evt);
            }
        });
        jPanel1.add(txtto);
        txtto.setBounds(960, 320, 130, 30);

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "क्रमांक", "प्राप्त तारीख", "से", "को", "टिप्पणी"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 590, 1120, 60);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("प्रिंट");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(120, 210, 90, 30);

        txtm.setColumns(20);
        txtm.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtm.setRows(5);
        jScrollPane2.setViewportView(txtm);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(960, 410, 210, 96);

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("अंतिम डेटा प्रविष्टि");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(190, 560, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            // TODO add your handling code here:
            pstmt=con.prepareStatement("insert into ig_f(serial_no,recieved_date,from1,letter_no,letter_no_date,to1,remarks,matter)values(?,?,?,?,?,?,?,?)");
            String n=txtsno.getText();
            n=n.trim();
            String letter_no=txtletter_no.getText();
            letter_no=letter_no.trim();
            String to=txtto.getText();
            to=to.trim();
            String remarks=txtremarks.getText();
            String r=txtfrom1.getSelectedItem().toString();
            String d1=((JTextField)txtrecieved_date.getDateEditor().getUiComponent()).getText();
            d1=d1.trim();
            String d2=((JTextField)txtletter_no_date.getDateEditor().getUiComponent()).getText();
            d2=d2.trim();
            if(r.equals("others"))
            {
                r=JOptionPane.showInputDialog("Plese Enter Your Range");
            } r=r.trim();
            if(n.length()>0 &&letter_no.length()>0&&d1.length()>0&&d2.length()>0 && to.length()>0 &&r.length()>0)
            {
            
                
            String m=txtm.getText();
            pstmt.setString(1,n);
            pstmt.setString(2,d1);
            pstmt.setString(5,d2);
            pstmt.setString(3,r);
            pstmt.setString(4,letter_no);
            pstmt.setString(6,to);
            pstmt.setString(7,remarks);
            pstmt.setString(8,m);
            int i=pstmt.executeUpdate();
            pstmt.clearParameters();
            if(i>=0)
            {
                JOptionPane.showMessageDialog(null,"Data inserted successfully","Data Insertion",JOptionPane.PLAIN_MESSAGE);
                txtm.setText("");
                try {
                    // TODO add your handling code here:
                    pstmt=con.prepareStatement("update sp set serial_no=?,date=?,to=?,from1=?,remarks=? where pref_no=?");
                    String n1=txtsno.getText();
                    String to1=txtto.getText();
                    String remarks1=txtremarks.getText();
                    pstmt.setString(1,n1);
                    pstmt.setString(2,((JTextField)txtrecieved_date.getDateEditor().getUiComponent()).getText());
                    pstmt.setString(4,r);
                    pstmt.setString(3,to1);
                    pstmt.setString(5,remarks1);
                    int p=1;
                    pstmt.setInt(6,p);
                    int i1=pstmt.executeUpdate();
                    pstmt.clearParameters();
                    if(i1>=0)
                    {
                        //JOptionPane.showMessageDialog(null,"Data inserted successfully","Data Insertion",JOptionPane.PLAIN_MESSAGE);
                        txtm.setText("");
                    }
                    else
                    {
                        //JOptionPane.showMessageDialog(null,"Data cannot be inserted","Insertion error",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    // JOptionPane.showMessageDialog(null,"Please check letter number"+ex,"Insertion  alert",JOptionPane.ERROR_MESSAGE);

                }
               last_data();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Data cannot be inserted","Insertion error",JOptionPane.ERROR_MESSAGE);
            }
        }
            else
            {
                 JOptionPane.showMessageDialog(null,"Plese check your important input","Insertion error",JOptionPane.ERROR_MESSAGE);   
                    }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Please check letter number","Insertion  alert",JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      ig_to_from ob=new ig_to_from();
        ob.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ig_f ob=new ig_f();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtremarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremarksActionPerformed

    private void txttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       ig_f ob=new ig_f();
        ob.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ig_from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ig_from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ig_from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ig_from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ig_from().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton submit;
    private javax.swing.JComboBox<String> txtfrom1;
    private javax.swing.JTextField txtletter_no;
    private com.toedter.calendar.JDateChooser txtletter_no_date;
    private javax.swing.JTextArea txtm;
    private com.toedter.calendar.JDateChooser txtrecieved_date;
    private javax.swing.JTextField txtremarks;
    private javax.swing.JTextField txtsno;
    private javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables
}
