/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
 import java.sql.*;
import java.sql.DriverManager;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MADHURENDRA PURBAY
 */
public class ig_to extends javax.swing.JFrame {
       Connection con=null;
    PreparedStatement pstmt=null;
void last_data_to()
    {
         try
        {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from sp where pref_no=2 ");
            String srno;
            String from;
            String to,dat,remark,date = null;
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while (true)
            {
                int c=tm.getRowCount();
                if(c==0)
                break;
                else
                tm.removeRow(0);
            }
            while(rs.next())
            {
                srno=rs.getString("serial_no");
                from=rs.getString("from1");
                to=rs.getString("to");
                dat=rs.getString("date");
                remark=rs.getString("remarks");
                try
                {
                    SimpleDateFormat simpledateformat1 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
                    java.util.Date tempDate1=simpledateformat1.parse(dat);
                    SimpleDateFormat outputDateFormat1 = new SimpleDateFormat("dd-MMM-yyyy");
                    //System.out.println("Output date is = "+outputDateFormat.format(tempDate));
                    date=outputDateFormat1.format(tempDate1);
                } catch (ParseException ex)
                {
                    System.out.println("Parse Exception");
                }

                Object kk[]={srno,date,to,from,remark};
                tm.addRow(kk);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connection "+e);
        }
    }
    /**
     * Creates new form ig_to
     */
    public ig_to() {
        initComponents();
         try
        {
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\dispatch.accdb");
        }
        catch(Exception e)
        {
            System.out.println(e);
             JOptionPane.showMessageDialog(null,"Database connection error","Error",JOptionPane.ERROR_MESSAGE);
        }
last_data_to();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtsno = new javax.swing.JTextField();
        txtd = new com.toedter.calendar.JDateChooser();
        txtremark = new javax.swing.JTextField();
        txtfrom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        submit1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtsno1 = new javax.swing.JTextField();
        txtd1 = new com.toedter.calendar.JDateChooser();
        txtremark1 = new javax.swing.JTextField();
        txtfrom1 = new javax.swing.JTextField();
        txtr1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        submit2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtsno2 = new javax.swing.JTextField();
        txtd2 = new com.toedter.calendar.JDateChooser();
        txtremark2 = new javax.swing.JTextField();
        txtfrom2 = new javax.swing.JTextField();
        txtr2 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        submit3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        txtsno3 = new javax.swing.JTextField();
        txtd3 = new com.toedter.calendar.JDateChooser();
        txtremark3 = new javax.swing.JTextField();
        txtfrom3 = new javax.swing.JTextField();
        txtr3 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtr = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 10, 600, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Developed By: Madhurendra & Vishal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 650, 240, 60);

        submit.setBackground(new java.awt.Color(204, 204, 204));
        submit.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 102, 102));
        submit.setText("जमा करें");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(900, 430, 110, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("वापस");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(180, 420, 100, 30);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("खोज");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1030, 220, 110, 30);

        txtsno.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtsno);
        txtsno.setBounds(200, 320, 70, 30);

        txtd.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txtd);
        txtd.setBounds(340, 320, 140, 30);

        txtremark.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtremark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremarkActionPerformed(evt);
            }
        });
        jPanel1.add(txtremark);
        txtremark.setBounds(1020, 320, 180, 30);

        txtfrom.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfromActionPerformed(evt);
            }
        });
        jPanel1.add(txtfrom);
        txtfrom.setBounds(810, 320, 130, 30);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("अंतिम डेटा प्रविष्टि");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 500, 190, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("प्रिंट");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 210, 90, 30);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("प्रेषण खंड(जावक)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 150, 250, 40);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("पुलिस महानिरीक्षक");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(650, 210, 230, 30);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("क्रमांक");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 280, 70, 30);

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText(" तारीख");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 280, 120, 30);

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("को");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(590, 280, 50, 30);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("से");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(820, 280, 40, 30);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText(" टिप्पणी");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1520, 280, 0, 30);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText(" टिप्पणी");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1040, 280, 120, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(400, 10, 600, 150);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Developed By: Madhurendra & Vishal");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 650, 240, 60);

        submit1.setBackground(new java.awt.Color(204, 204, 204));
        submit1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        submit1.setForeground(new java.awt.Color(0, 102, 102));
        submit1.setText("जमा करें");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        jPanel2.add(submit1);
        submit1.setBounds(900, 430, 110, 30);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("वापस");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(180, 420, 100, 30);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("खोज");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(1030, 220, 110, 30);

        txtsno1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel2.add(txtsno1);
        txtsno1.setBounds(200, 320, 70, 30);

        txtd1.setDateFormatString("dd-MMM-yyyy");
        jPanel2.add(txtd1);
        txtd1.setBounds(340, 320, 140, 30);

        txtremark1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtremark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremark1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtremark1);
        txtremark1.setBounds(1020, 320, 180, 30);

        txtfrom1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtfrom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfrom1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtfrom1);
        txtfrom1.setBounds(810, 320, 130, 30);

        txtr1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DGP Chattisgarh", "ADG (Admn.)", "IG (Admn.)", "DIG (Admn.)", "AIG (Admn.)", "AIG (Acct./Welfare/Traffic)", "DSP (Admn.)", "DSP (Welfare)", "ADG (INT)", "DIG (SB)", "AIG (Security)", "ASP (Admn.,SB)", "DSP (SB)", "DG (SIB/ANO)", "DIG (ANO)", "DIG (SIB)", "AIG (ANO)", "ASP (SIB)", "ADG (Rail/Traffic)", "AIG (Rail/Traffic)", "ADG (P/P&Tech.Service)", "IGP  (P/P&Tech.Service)", "ADG (CAF & STF)", "AIG (Training)", "ADG (CID)", "IG (AJK)", "IG (CID)", "AIG (CID)", "AIG (CID/AJK)", "others", " " }));
        txtr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtr1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtr1);
        txtr1.setBounds(550, 320, 180, 30);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Last data Entry");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(280, 490, 190, 30);

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("प्रिंट");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(140, 210, 90, 30);

        jLabel15.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("प्रेषण खंड");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(670, 150, 200, 40);

        jLabel16.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("पुलिस महानिरीक्षक");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(650, 210, 230, 30);

        jLabel17.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("क्रमांक");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(210, 280, 70, 30);

        jLabel18.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText(" तारीख");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(340, 280, 120, 30);

        jLabel19.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("को");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(590, 280, 50, 30);

        jLabel20.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("से");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(820, 280, 40, 30);

        jLabel21.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText(" टिप्पणी");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(1520, 280, 0, 30);

        jLabel22.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText(" टिप्पणी");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(1040, 280, 120, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel3.add(jLabel23);
        jLabel23.setBounds(400, 10, 600, 150);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Developed By: Madhurendra & Vishal");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(40, 650, 240, 60);

        submit2.setBackground(new java.awt.Color(204, 204, 204));
        submit2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        submit2.setForeground(new java.awt.Color(0, 102, 102));
        submit2.setText("जमा करें");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });
        jPanel3.add(submit2);
        submit2.setBounds(900, 430, 110, 30);

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setText("वापस");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(180, 420, 100, 30);

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 102));
        jButton8.setText("खोज");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(1030, 220, 110, 30);

        txtsno2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel3.add(txtsno2);
        txtsno2.setBounds(200, 320, 70, 30);

        txtd2.setDateFormatString("dd-MMM-yyyy");
        jPanel3.add(txtd2);
        txtd2.setBounds(340, 320, 140, 30);

        txtremark2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtremark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremark2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtremark2);
        txtremark2.setBounds(1020, 320, 180, 30);

        txtfrom2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtfrom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfrom2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtfrom2);
        txtfrom2.setBounds(810, 320, 130, 30);

        txtr2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtr2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DGP Chattisgarh", "ADG (Admn.)", "IG (Admn.)", "DIG (Admn.)", "AIG (Admn.)", "AIG (Acct./Welfare/Traffic)", "DSP (Admn.)", "DSP (Welfare)", "ADG (INT)", "DIG (SB)", "AIG (Security)", "ASP (Admn.,SB)", "DSP (SB)", "DG (SIB/ANO)", "DIG (ANO)", "DIG (SIB)", "AIG (ANO)", "ASP (SIB)", "ADG (Rail/Traffic)", "AIG (Rail/Traffic)", "ADG (P/P&Tech.Service)", "IGP  (P/P&Tech.Service)", "ADG (CAF & STF)", "AIG (Training)", "ADG (CID)", "IG (AJK)", "IG (CID)", "AIG (CID)", "AIG (CID/AJK)", "others", " " }));
        txtr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtr2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtr2);
        txtr2.setBounds(550, 320, 180, 30);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 51));
        jLabel25.setText("Last data Entry");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(280, 490, 190, 30);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 102));
        jButton9.setText("प्रिंट");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(140, 210, 90, 30);

        jLabel26.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("प्रेषण खंड");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(670, 150, 200, 40);

        jLabel27.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("पुलिस महानिरीक्षक");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(650, 210, 230, 30);

        jLabel28.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("क्रमांक");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(210, 280, 70, 30);

        jLabel29.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText(" तारीख");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(340, 280, 120, 30);

        jLabel30.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("को");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(590, 280, 50, 30);

        jLabel31.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("से");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(820, 280, 40, 30);

        jLabel32.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText(" टिप्पणी");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(1520, 280, 0, 30);

        jLabel33.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 102));
        jLabel33.setText(" टिप्पणी");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(1040, 280, 120, 30);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel4.add(jLabel34);
        jLabel34.setBounds(400, 10, 600, 150);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 153, 153));
        jLabel35.setText("Developed By: Madhurendra & Vishal");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(40, 650, 240, 60);

        submit3.setBackground(new java.awt.Color(204, 204, 204));
        submit3.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        submit3.setForeground(new java.awt.Color(0, 102, 102));
        submit3.setText("जमा करें");
        submit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit3ActionPerformed(evt);
            }
        });
        jPanel4.add(submit3);
        submit3.setBounds(900, 430, 110, 30);

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 102));
        jButton10.setText("वापस");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);
        jButton10.setBounds(180, 420, 100, 30);

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 102));
        jButton11.setText("खोज");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);
        jButton11.setBounds(1030, 220, 110, 30);

        txtsno3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel4.add(txtsno3);
        txtsno3.setBounds(200, 320, 70, 30);

        txtd3.setDateFormatString("dd-MMM-yyyy");
        jPanel4.add(txtd3);
        txtd3.setBounds(340, 320, 140, 30);

        txtremark3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtremark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremark3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtremark3);
        txtremark3.setBounds(1020, 320, 180, 30);

        txtfrom3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtfrom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfrom3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtfrom3);
        txtfrom3.setBounds(810, 320, 130, 30);

        txtr3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtr3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DGP Chattisgarh", "ADG (Admn.)", "IG (Admn.)", "DIG (Admn.)", "AIG (Admn.)", "AIG (Acct./Welfare/Traffic)", "DSP (Admn.)", "DSP (Welfare)", "ADG (INT)", "DIG (SB)", "AIG (Security)", "ASP (Admn.,SB)", "DSP (SB)", "DG (SIB/ANO)", "DIG (ANO)", "DIG (SIB)", "AIG (ANO)", "ASP (SIB)", "ADG (Rail/Traffic)", "AIG (Rail/Traffic)", "ADG (P/P&Tech.Service)", "IGP  (P/P&Tech.Service)", "ADG (CAF & STF)", "AIG (Training)", "ADG (CID)", "IG (AJK)", "IG (CID)", "AIG (CID)", "AIG (CID/AJK)", "others", " " }));
        txtr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtr3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtr3);
        txtr3.setBounds(550, 320, 180, 30);

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 51, 51));
        jLabel36.setText("Last data Entry");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(280, 490, 190, 30);

        jButton12.setBackground(new java.awt.Color(204, 204, 204));
        jButton12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 102, 102));
        jButton12.setText("प्रिंट");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(140, 210, 90, 30);

        jLabel37.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 153, 153));
        jLabel37.setText("प्रेषण खंड");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(670, 150, 200, 40);

        jLabel38.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("पुलिस महानिरीक्षक");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(650, 210, 230, 30);

        jLabel39.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 102));
        jLabel39.setText("क्रमांक");
        jPanel4.add(jLabel39);
        jLabel39.setBounds(210, 280, 70, 30);

        jLabel40.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 102));
        jLabel40.setText(" तारीख");
        jPanel4.add(jLabel40);
        jLabel40.setBounds(340, 280, 120, 30);

        jLabel41.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 102));
        jLabel41.setText("को");
        jPanel4.add(jLabel41);
        jLabel41.setBounds(590, 280, 50, 30);

        jLabel42.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 102));
        jLabel42.setText("से");
        jPanel4.add(jLabel42);
        jLabel42.setBounds(820, 280, 40, 30);

        jLabel43.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 102));
        jLabel43.setText(" टिप्पणी");
        jPanel4.add(jLabel43);
        jLabel43.setBounds(1520, 280, 0, 30);

        jLabel44.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 102));
        jLabel44.setText(" टिप्पणी");
        jPanel4.add(jLabel44);
        jLabel44.setBounds(1040, 280, 120, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 0, 0);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "क्रमांक", "तारीख", "को", "से", "टिप्पणी"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 530, 1120, 60);

        txtr.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IG  Bastar", "IG  Bilapsur", "IG  Durg", "IG  Raipur", "IG  Sargoja  ", "others" }));
        jPanel1.add(txtr);
        txtr.setBounds(540, 320, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            // TODO add your handling code here:
            pstmt=con.prepareStatement("insert into ig_to(serial_no,date,to1,from1,remarks)values(?,?,?,?,?)");
            String n=txtsno.getText();
            n=n.trim();
            String r=txtr.getSelectedItem().toString();
            String d=((JTextField)txtd.getDateEditor().getUiComponent()).getText();
            d=d.trim();
            if(r.equals("others"))
            {
                r=JOptionPane.showInputDialog("Plese Enter Your Range");
            }
            String f=txtfrom.getText();
            f=f.trim();
            r=r.trim();
            if(n.length()>0&&d.length()>0&&f.length()>0&&r.length()>0)
            {
            String remark=txtremark.getText();
            pstmt.setString(1,n);
            pstmt.setString(2,d);
            pstmt.setString(3,r);
            pstmt.setString(4,f);
            pstmt.setString(5,remark);
            int i=pstmt.executeUpdate();
            pstmt.clearParameters();
            if(i>=0)
            {
                JOptionPane.showMessageDialog(null,"Data inserted successfully","Data Insertion",JOptionPane.PLAIN_MESSAGE);
                txtsno.setText("");
                txtfrom.setText("");
                txtremark.setText("");

                try {
                    // TODO add your handling code here:
                    pstmt=con.prepareStatement("update sp set serial_no=?,date=?,to=?,from1=?,remarks=? where pref_no=?");
                    pstmt.setString(1,n);
                    pstmt.setString(2,((JTextField)txtd.getDateEditor().getUiComponent()).getText());
                    pstmt.setString(4,f);
                    pstmt.setString(3,r);
                    pstmt.setString(5,remark);
                    int p=2;
                    pstmt.setInt(6,p);
                    int i1=pstmt.executeUpdate();
                    pstmt.clearParameters();
                    if(i1>=0)
                    {
                        //JOptionPane.showMessageDialog(null,"Data inserted successfully","Data Insertion",JOptionPane.PLAIN_MESSAGE);
                    }
                    else
                    {
                        //  JOptionPane.showMessageDialog(null,"Data cannot be inserted","Insertion error",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    //JOptionPane.showMessageDialog(null,"Please check letter number"+ex,"Insertion  alert",JOptionPane.ERROR_MESSAGE);

                }
                last_data_to();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Data cannot be inserted","Insertion error",JOptionPane.ERROR_MESSAGE);
            }
        } else
            {
                 JOptionPane.showMessageDialog(null,"Plese check your important input","Insertion error",JOptionPane.ERROR_MESSAGE);   
                    }
       
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Please check letter number","Insertion  alert",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       ig_to_from ob=new ig_to_from();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       ig_t ob=new ig_t();
      ob.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtremarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremarkActionPerformed

    private void txtfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfromActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ig_t ob=new ig_t();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtremark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremark1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremark1ActionPerformed

    private void txtfrom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfrom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfrom1ActionPerformed

    private void txtr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtr1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtremark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremark2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremark2ActionPerformed

    private void txtfrom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfrom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfrom2ActionPerformed

    private void txtr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtr2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void submit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtremark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremark3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremark3ActionPerformed

    private void txtfrom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfrom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfrom3ActionPerformed

    private void txtr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtr3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtr3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ig_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ig_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ig_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ig_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ig_to().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JButton submit2;
    private javax.swing.JButton submit3;
    private com.toedter.calendar.JDateChooser txtd;
    private com.toedter.calendar.JDateChooser txtd1;
    private com.toedter.calendar.JDateChooser txtd2;
    private com.toedter.calendar.JDateChooser txtd3;
    private javax.swing.JTextField txtfrom;
    private javax.swing.JTextField txtfrom1;
    private javax.swing.JTextField txtfrom2;
    private javax.swing.JTextField txtfrom3;
    private javax.swing.JComboBox<String> txtr;
    private javax.swing.JComboBox<String> txtr1;
    private javax.swing.JComboBox<String> txtr2;
    private javax.swing.JComboBox<String> txtr3;
    private javax.swing.JTextField txtremark;
    private javax.swing.JTextField txtremark1;
    private javax.swing.JTextField txtremark2;
    private javax.swing.JTextField txtremark3;
    private javax.swing.JTextField txtsno;
    private javax.swing.JTextField txtsno1;
    private javax.swing.JTextField txtsno2;
    private javax.swing.JTextField txtsno3;
    // End of variables declaration//GEN-END:variables
}
