/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
import java.sql.*;
import java.sql.DriverManager;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MADHURENDRA PURBAY
 */
public class police_f extends javax.swing.JFrame {
         Connection con=null;
    PreparedStatement pstmt=null;

    /**
     * Creates new form police_f
     */
    public police_f() {
        initComponents();
          try
        {
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\dispatch_p.accdb");
        }
        catch(Exception e)
        {
            System.out.println(e);
             JOptionPane.showMessageDialog(null,"Database connection error","Error",JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnsl = new javax.swing.JButton();
        btnb = new javax.swing.JButton();
        txtn = new javax.swing.JTextField();
        txtd1 = new com.toedter.calendar.JDateChooser();
        txtd2 = new com.toedter.calendar.JDateChooser();
        btns1 = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 10, 600, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Developed By: Madhurendra & Vishal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 690, 240, 60);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("पुलिस मुख्यालय");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(630, 150, 180, 30);

        btnsl.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        btnsl.setForeground(new java.awt.Color(0, 102, 102));
        btnsl.setText("खोज");
        btnsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnslActionPerformed(evt);
            }
        });
        jPanel1.add(btnsl);
        btnsl.setBounds(440, 310, 110, 30);

        btnb.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        btnb.setForeground(new java.awt.Color(0, 102, 102));
        btnb.setText("वापस");
        btnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbActionPerformed(evt);
            }
        });
        jPanel1.add(btnb);
        btnb.setBounds(120, 380, 100, 30);

        txtn.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnActionPerformed(evt);
            }
        });
        jPanel1.add(txtn);
        txtn.setBounds(260, 310, 160, 30);

        txtd1.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txtd1);
        txtd1.setBounds(590, 310, 130, 30);

        txtd2.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txtd2);
        txtd2.setBounds(740, 310, 140, 30);

        btns1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        btns1.setForeground(new java.awt.Color(0, 102, 102));
        btns1.setText("खोज");
        btns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns1ActionPerformed(evt);
            }
        });
        jPanel1.add(btns1);
        btns1.setBounds(900, 310, 110, 30);

        btnprint.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        btnprint.setForeground(new java.awt.Color(0, 102, 102));
        btnprint.setText("प्रिंट");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint);
        btnprint.setBounds(910, 200, 110, 40);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("पत्र संख्या");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 270, 130, 30);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("महीना वर्ष");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(700, 270, 120, 30);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("या");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(560, 310, 30, 30);

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "क्रमांक", " प्राप्त तारीख", "से", "पत्र संख्या", "पत्र नंबर की तारीख", "को", "मामला", "टिप्पणी"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(120);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(110, 460, 1180, 180);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("खोज अनुभाग(आवक)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(640, 190, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnslActionPerformed
        // TODO add your handling code here:
        try{ //int tot=0;
            pstmt=con.prepareStatement("select * from police_f where letter_no=?");
            String num=txtn.getText();
            pstmt.setString(1, num);
            pstmt.execute();
            ResultSet  rs1=pstmt.getResultSet();
            String from,srno,let_no,to;
            String date1 = null,d1,d2,date2=null;
            String mat,remark;
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while (true)
            {
                int c=tm.getRowCount();
                if(c==0)
                break;
                else
                tm.removeRow(0);
            }

            while(rs1.next())
            {
                 srno=rs1.getString("serial_no");
                to=rs1.getString("to1");
                remark=rs1.getString("remarks");
                from=rs1.getString("from1");
                d1=rs1.getString("recieved_date");
                d2=rs1.getString("letter_no_date");
                   mat=rs1.getString("matter");
                   let_no=rs1.getString("letter_no");

                try
                {
                    SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
                    java.util.Date tempDate1=simpledateformat.parse(d1);
                    java.util.Date tempDate2=simpledateformat.parse(d2);
                    SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");
                    //System.out.println("Output date is = "+outputDateFormat.format(tempDate));
                    date1=outputDateFormat.format(tempDate1);
                    date2=outputDateFormat.format(tempDate2);
                } catch (ParseException ex)
                {
                    System.out.println("Parse Exception"+ex);
                }

                Object kk[]={srno,date1,from,let_no,date2,to,mat,remark};
                tm.addRow(kk);
            }
            //  selectps.clearParameters();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"couldnotfound  "+e);
        }
    }//GEN-LAST:event_btnslActionPerformed

    private void btnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbActionPerformed
        // TODO add your handling code here:
        police_from ob=new police_from();
        ob.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnbActionPerformed

    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnActionPerformed

    private void btns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns1ActionPerformed
        // TODO add your handling code here:
        try{ //int tot=0;
            pstmt=con.prepareStatement("select * from police_f where recieved_date between ? and ?");
            pstmt.setString(1,((JTextField)txtd1.getDateEditor().getUiComponent()).getText());
            pstmt.setString(2,((JTextField)txtd2.getDateEditor().getUiComponent()).getText());

            pstmt.execute();
            ResultSet  rs1=pstmt.getResultSet();
            String from,srno,let_no,to;
            String date1 = null,d1,d2,date2=null;
            String mat,remark;

            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while (true)
            {
                int c=tm.getRowCount();
                if(c==0)
                break;
                else
                tm.removeRow(0);
            }

            while(rs1.next())
            {
                 srno=rs1.getString("serial_no");
                to=rs1.getString("to1");
                remark=rs1.getString("remarks");
                from=rs1.getString("from1");
                d1=rs1.getString("recieved_date");
                d2=rs1.getString("letter_no_date");
                   mat=rs1.getString("matter");
                   let_no=rs1.getString("letter_no");
              try
                {
                    SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
                    java.util.Date tempDate1=simpledateformat.parse(d1);
                    java.util.Date tempDate2=simpledateformat.parse(d2);
                    SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");
                    //System.out.println("Output date is = "+outputDateFormat.format(tempDate));
                    date1=outputDateFormat.format(tempDate1);
                    date2=outputDateFormat.format(tempDate1);
                } catch (ParseException ex)
                {
                    System.out.println("Parse Exception"+ex);
                }

                Object kk[]={srno,date1,from,let_no,date2,to,mat,remark};
                tm.addRow(kk);
            }
            //  selectps.clearParameters();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"couldnotfound mkp "+e);
        }
    }//GEN-LAST:event_btns1ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header= new MessageFormat("Inspector General of police ");
        MessageFormat footer=new MessageFormat ("page{0,number,integer}");
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.out.println(e);
            //System.err.format("can not print %s %n"e.getMessage());
        }
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(police_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(police_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(police_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(police_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new police_f().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnb;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btns1;
    private javax.swing.JButton btnsl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser txtd1;
    private com.toedter.calendar.JDateChooser txtd2;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
