/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
import java.sql.*;
import java.sql.DriverManager;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MADHURENDRA PURBAY
 */
public class police_to extends javax.swing.JFrame {
           Connection con=null;
    PreparedStatement pstmt=null;
 void last_data_to()
    {
         try
        {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from sp where pref_no=4 ");
            String srno;
            String from;
            String to,dat,remark,date = null;
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while (true)
            {
                int c=tm.getRowCount();
                if(c==0)
                break;
                else
                tm.removeRow(0);
            }
            while(rs.next())
            {
                srno=rs.getString("serial_no");
                from=rs.getString("from1");
                to=rs.getString("to");
                dat=rs.getString("date");
                remark=rs.getString("remarks");
                try
                {
                    SimpleDateFormat simpledateformat1 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
                    java.util.Date tempDate1=simpledateformat1.parse(dat);
                    SimpleDateFormat outputDateFormat1 = new SimpleDateFormat("dd-MMM-yyyy");
                    //System.out.println("Output date is = "+outputDateFormat.format(tempDate));
                    date=outputDateFormat1.format(tempDate1);
                } catch (ParseException ex)
                {
                    System.out.println("Parse Exception");
                }

                Object kk[]={srno,date,to,from,remark};
                tm.addRow(kk);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connection "+e);
        }
    }
   
    /**
     * Creates new form police_to
     */
    public police_to() {
        initComponents();
         try
        {
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\dispatch_p.accdb");
        }
        catch(Exception e)
        {
            System.out.println(e);
             JOptionPane.showMessageDialog(null,"Database connection error","Error",JOptionPane.ERROR_MESSAGE);
        }
last_data_to();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtsno = new javax.swing.JTextField();
        txtd = new com.toedter.calendar.JDateChooser();
        txtremark = new javax.swing.JTextField();
        txtfrom = new javax.swing.JTextField();
        txtr = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 10, 600, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Developed By: Madhurendra & Vishal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 650, 240, 60);

        submit.setBackground(new java.awt.Color(204, 204, 204));
        submit.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 102, 102));
        submit.setText("जमा करें");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(900, 430, 110, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("वापस");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(180, 420, 100, 30);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("खोज");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1030, 220, 110, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("प्रिंट");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 210, 90, 30);

        txtsno.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtsno);
        txtsno.setBounds(200, 320, 70, 30);

        txtd.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txtd);
        txtd.setBounds(340, 320, 140, 30);

        txtremark.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtremark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremarkActionPerformed(evt);
            }
        });
        jPanel1.add(txtremark);
        txtremark.setBounds(1020, 320, 180, 30);

        txtfrom.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfromActionPerformed(evt);
            }
        });
        jPanel1.add(txtfrom);
        txtfrom.setBounds(810, 320, 130, 30);

        txtr.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DGP Chattisgarh", "Acct./Welfare/Traffic", "ADMN", "AJK", "ANO", "CAF & STF", "CID", "INT", "P/P&Tech.ServiceSB", "Security", "SIB", "Rail/Traffic", "Training", "Welfare", "others" }));
        txtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrActionPerformed(evt);
            }
        });
        jPanel1.add(txtr);
        txtr.setBounds(550, 320, 180, 30);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("प्रेषण खंड");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(630, 150, 200, 40);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("पुलिस मुख्यालय");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(630, 210, 190, 30);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("क्रमांक");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 280, 70, 30);

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText(" तारीख");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 280, 120, 30);

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("को");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(590, 280, 50, 30);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("से");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(820, 280, 40, 30);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText(" टिप्पणी");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1040, 280, 120, 30);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("अंतिम डेटा प्रविष्टि");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 500, 190, 30);

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "क्रमांक", "तारीख", "को", "से", "टिप्पणी"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 540, 1120, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            // TODO add your handling code here:
             pstmt=con.prepareStatement("insert into police_to(serial_no,date,to1,from1,remarks)values(?,?,?,?,?)");
            String n=txtsno.getText();
            n=n.trim();
            String r=txtr.getSelectedItem().toString();
            String d=((JTextField)txtd.getDateEditor().getUiComponent()).getText();
            d=d.trim();
            if(r.equals("others"))
            {
                r=JOptionPane.showInputDialog("Plese Enter Your Range");
            }
            String f=txtfrom.getText();
            f=f.trim();
            r=r.trim();
             if(n.length()>0&&d.length()>0&&f.length()>0&&r.length()>0)
            {
            String remark=txtremark.getText();
            pstmt.setString(1,n);
            pstmt.setString(2,d);
            pstmt.setString(3,r);
            pstmt.setString(4,f);
            pstmt.setString(5,remark);
            int i=pstmt.executeUpdate();
            pstmt.clearParameters();
            if(i>=0)
            {
                JOptionPane.showMessageDialog(null,"Data inserted successfully","Data Insertion",JOptionPane.PLAIN_MESSAGE);
                txtsno.setText("");
                txtfrom.setText("");
                txtremark.setText("");

                try {
                    // TODO add your handling code here:
                    pstmt=con.prepareStatement("update sp set serial_no=?,date=?,to=?,from1=?,remarks=? where pref_no=?");
                    pstmt.setString(1,n);
                    pstmt.setString(2,((JTextField)txtd.getDateEditor().getUiComponent()).getText());
                    pstmt.setString(4,f);
                    pstmt.setString(3,r);
                    pstmt.setString(5,remark);
                    int p=4;
                    pstmt.setInt(6,p);
                    int i1=pstmt.executeUpdate();
                    pstmt.clearParameters();
                    if(i1>=0)
                    {
                        //JOptionPane.showMessageDialog(null,"Data inserted successfully","Data Insertion",JOptionPane.PLAIN_MESSAGE);
                    }
                    else
                    {
                        //  JOptionPane.showMessageDialog(null,"Data cannot be inserted","Insertion error",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    //JOptionPane.showMessageDialog(null,"Please check letter number"+ex,"Insertion  alert",JOptionPane.ERROR_MESSAGE);

                }
                  last_data_to();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Data cannot be inserted","Insertion error",JOptionPane.ERROR_MESSAGE);
            }
            } else
            {
                 JOptionPane.showMessageDialog(null,"Plese check your important input","Insertion error",JOptionPane.ERROR_MESSAGE);   
                    }
       
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Please check letter number","Insertion  alert",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         police_to_from ob=new police_to_from();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        police_t ob=new police_t();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       police_t ob=new police_t();
       ob.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtremarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremarkActionPerformed

    private void txtfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfromActionPerformed

    private void txtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(police_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(police_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(police_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(police_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new police_to().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton submit;
    private com.toedter.calendar.JDateChooser txtd;
    private javax.swing.JTextField txtfrom;
    private javax.swing.JComboBox<String> txtr;
    private javax.swing.JTextField txtremark;
    private javax.swing.JTextField txtsno;
    // End of variables declaration//GEN-END:variables
}
